import { ILocalizedStrings } from "./Strings";

const ru: ILocalizedStrings = {
    //settings view
    refresh1m: "1 минута",
    refresh5m: "5 минут",
    refresh10m: "10 минут",
    refreshdebug: "(debug) 10 секунд",
    sortPatternWeight: "Вес, Дата",
    sortPatternAssigned: '"Назначен", Дата',
    sortPatternId: "ID",
    notifModeAll: "Все",
    notifModeMine: "Только мои",
    notifModeNone: "Никакие",
    localeAuto: "Автоопределение",
    localeEn: "Английский",
    localeRu: "Русский",
    updateStateChecking: "Проверка наличия обновлений...",
    updateStateDownloading: "Загрузка обновлений...",
    updateStateReady: "Обновления готовы к установке. Нажмите чтобы начать",
    updateStateNone: "Проверить наличие обновлений",
    settingsHeader: "Настройки",
    editTfsSettingsBtn: "Настройки TFS и учетной записи",
    settingsBackButton: "Сохранить",
    settingsQueriesHeader: "Отслеживаемые запросы",
    settingsOthersHeader: "Другие настройки",
    ddLocalesLabel: "Язык: ",
    ddRefreshLabel: "Интервал обновления запросов: ",
    ddShowNotifLabel: "Показывать уведомления: ",
    cbIconLabel: "Менять иконку приложения только от событий, связанных с моими задачами",
    cbAutostartLabel: "Запускать вместе с Windows (применяется при перезапуске приложения)",
    settingsCreditsHeader: "Автор и обновления",
    versionWord: "Версия",
    //sel queries view
    loading: "Загрузка...",
    noQueriesAvailable: "Нет ни одного доступного вам запроса. Убедитесь, что добавили нужные в 'Избранное' в TFS.",
    selQHeader: "Выбор запросов",
    cancel: "Отмена",
    add: "Добавить",
    note: "Важно!",
    selqNote1: "Здесь видны только те запросы, которые находятся в вашем ",
    selqNote2: "Избранном",
    selqNote3: " и ",
    selqNote4: "еще не были добавлены",
    selqNote5: " в список отслеживания.",
    selqAvailableHeader: "Доступные запросы",
    refresh: "Обновить",
    //main view
    noQueriesToWatch: "Нет отслеживаемых запросов",
    noQueriesToWatchText: "Добавьте их в настройках",
    mainHeader: "Запросы",
    settings: "Настройки",
    updateArrived: "Обновление доступно!",
    updateArrivedText1: "Обновление Flowerpot готово. ",
    updateArrivedText2: "его нажав на кнопку или перезапустив приложение.",
    install: "Установите",
    //error view
    errorHeader: "Ошибка :(",
    errorMsg: "Что-то пошло не так!",
    errorDesc1: "Вы можете вручную",
    errorDesc2: "страницу",
    errorDesc3: "Или проверить",
    errorDesc4: "на предмет корректности",
    tfsSettings: "Настройки TFS",
    //creds view
    validate: "Проверить",
    status: "Статус: ",
    credsNoteText: "Вы должны проверить введенные данные на корректность.",
    tfsPwd: "Пароль TFS",
    tfsUser: "Имя пользователя TFS (с доменом)",
    tfsPath: "Путь к TFS с именем коллекции (должен начинаться с 'http://' и заканчиваться '/')",
    credsHeader: "Учетные данные",
    save: "Сохранить",
    tfsHeader: "Настройки TFS и учетной записи",
    credsState1: "Не проверены",
    credsState2: "Проверка...",
    credsState3: "Сервер недоступен или путь к TFS не верный",
    credsState4: "Не верное имя пользователя или пароль",
    credsState5: "OK",
    //helpers
    throwNoTeams: "Не найдено доступных проектов",
    throwQueryLoading: "Ошибка при загрузке запроса",
    throwAuth: "Невозможно авторизоваться с предоставленными учетными данными, путь к TFS некорректен или проблемы с сетью",
    throwUnknown: "Что-то пошло не так во время обработки запроса",
    notifNewItem: ": новое",
    notifChangedItem: ": изменения",
    //comps
    timeSinceCreated: "Время с момента создания",
    revision: "Ревизия",
    priority: "Приоритет ",
    severity: "Важность ",
    addQuery: "Добавить запрос",
    actions: "Действия",
    ignoreNotif: "Игнор. уведом.",
    ignoreIcon: "Игнор. икон.",
    queryName: "Название запроса",
    teamProject: "Проект",
    sortPattern: "Сортировка результатов запроса: "
};

export default ru;
