export enum Actions {
    AppViewSet = "app/view-set",
    AppErrorSet = "app/error-set",
    AppShowWhatsNewSet = "app/show-whatsnew-set",
    AppSettingsSet = "app/settings-set",
    AppCurrentFestivalSet = "app/current-fest-set",
    AppUpdateStatusSet = "app/update-status-set",
    AppDialogSet = "app/dialog-set",
    AppLoadingInProgressListSet = "app/loading-in-progress-list-set",
    AppShowMineOnlySet = "app/show-mine-only-set",
    DataChangesCollectionClear = "data/changes-collection-clear",
    DataChangesCollectionSet = "data/changes-collection-set",
    DataChangesCollectionItemSet = "data/changes-collection-item-set",
    DataWorkItemsForQuerySet = "data/wi-for-query-set",
    SettingsSet = "settings/set",
    SettingsUpdate = "settings/update",
    SettingsMigrationsDonePush = "settings/migrations-done-push",
    SettingsListUpdate = "settings/list-update",
}
